### ISSUE TITLE
Circos checklist

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dictyaccess#5]
- [x] Make images clickable w/ redirect to full diagram
- [x] Solve issue with rendering thumbnails (possibly with web workers?)
- [x] Cut down on white space
- [x] Make wireframes
- [x] Make data stay rendered after mounting
- [x] Add zoom feature
- [x] Figure out how to click data and open page

Zoom feature possibility: https://github.com/chrvadala/react-svg-pan-zoom

**Comment by wildlifehexagon** [comment]
For click handling, `circosJS` has an events attribute that can be customized to handle these events.
